name: pretrain-sft
stages:
  - name: pretrain
    data_preset: shpak
    checkpoint_out: checkpoints/busel_kruk_pretrain_FINAL.pt
    params:
      profile_name: kruk-210m
      no_compile: true
      max_steps: auto
  - name: sft
    data_preset: shpak
    checkpoint_out: checkpoints/busel_kruk_sft_FINAL.pt
    params:
      profile_name: kruk-210m
      no_compile: true
      max_steps: 2000
global_params: {}
