name: busel-200m
stages:
  - name: pretrain
    data_preset: busel-200m
    checkpoint_out: checkpoints/busel_200m_FINAL.pt
    params:
      profile_name: busel-200m
      no_fp8: true
      batch_size: 112
  - name: sft
    resume: checkpoints/busel_200m_FINAL.pt
    data_preset: busel-200m
    params:
      profile_name: busel-200m
      no_compile: true
      data_glob: "data_train/sft/**/*.jsonl"
      sft_data_glob: "data_train/sft/**/*.jsonl"
      max_steps: 2000
      warmup_steps: 100
      sft_lr_scale: 0.3
global_params: {}
