name: verabey-67m
stages:
- name: pretrain
  data_preset: verabey-67m
  checkpoint_out: checkpoints/verabey-67m_pretrain_FINAL.pt
  params:
    profile_name: verabey-67m
    no_compile: true
    max_steps: auto
- name: sft
  data_preset: verabey-67m
  checkpoint_out: checkpoints/verabey-67m_sft_FINAL.pt
  params:
    profile_name: verabey-67m
    no_compile: true
    max_steps: 200
global_params: {}
