global:
  project_name: "bysel"
  device: "cuda"
  seed: 42
  precision: "bf16"

profiles:
  ziaziulia:
    model:
      d_model: 256
      n_layers: 12
      n_heads: 4
      expert_hidden: 512
      num_experts: 4
      top_k: 2
      vocab_size: 259
    data:
      data_path: "data_train"
      chunk_size: 512
      batch_size: 4
    training:
      max_steps: 15000
      learning_rate_muon: 0.0004
      learning_rate_adamw: 0.00004
      weight_decay: 0.1

  zubr:
    model:
      d_model: 1792
      n_layers: 32
      n_heads: 16
      expert_hidden: 2048
      num_experts: 64
      top_k: 2
      vocab_size: 259
    data:
      data_path: "data_train"
      chunk_size: 8192
      batch_size: 32
    training:
      max_steps: 80000
      learning_rate_muon: 0.0004
      learning_rate_adamw: 0.00004
      weight_decay: 0.1